### ISSUE TITLE
Make hologram works on Windows

### ISSUE THREAD

**Issue by gagarine** [trulia/hologram#117]
Hologram do not work on windows. I'm using the Power Shell. Ruby was installed with http://rubyinstaller.org and https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

I do have a hologram config files and it perfectly works on OSX.

```
PS C:\myProject> hologram
C:/Ruby200/lib/ruby/gems/2.0.0/gems/posix-spawn-0.3.8/lib/posix/
'which' is not recognized as an internal or external command,
operable program or batch file.
(?°?°)?? ???  Build not complete.
 Could not load config file, try 'hologram init' to get started
```

**Comment by GaryJones** [comment]
I've got this working for Mac, but another user using the same repo setup on Windows is still having trouble, even with 1.2.0.
Getting the same build failed errors as above, and notice about doing `hologram init`. Also, the `documentation_assets`, referencing cortana, are not being copied into the styleguide directory, so although it's partly working despite the warnings, the style guide doesn't look like it should.

`documentation_assets: assets/bower/cortana` doesn't seem to work for Windows (fine on Mac) - case matches the path in the repo.
`custom_markdown: assets/bower/cortana/CortanaMarkdownRenderer.rb` is copied fine.

Maybe `documentation_assets` are not having the slashes reversed or something daft to satisfy Windows?

**Comment by jdcantrell** [comment]
We just released version 1.3.0 to rubygems.org, could you test with the new version and report back? I know there were a few updates that should make Windows users much happier.

**Comment by robincornett** [comment]
Windows user reporting in. 1.3.0 seems to have helped a lot. The new output looks like:
![image](https://cloud.githubusercontent.com/assets/4853066/5818543/555377d4-a084-11e4-94e4-5f38eea63e7d.png)
I do not know what the warning means but hopefully it's helpful to you.

**Comment by jdcantrell** [comment]
The warning is from hologram parsing your source code, you have two documentation blocks with the same name ('d-small'). That said if your output is what you're looking for it, it's not a big worry. 

Thanks for the update though, I'm glad to hear it's working better.

**Comment by GaryJones** [comment]
Just confirming (Robin and I are working on the same project), and yes, there are indeed two documentation blocks with the name `d-small`; useful warning!
