### ISSUE TITLE
Hologram always assumes ERB files should be executed

### ISSUE THREAD

**Issue by adamsanderson** [trulia/hologram#123]
This might be a bit tricky to get right, but it appears that as of v1.1.0, Hologram assumes that any ERB file should be executed to generate a page in the style guide.

This probably makes sense if you're using it to generate a sample JSON file to give some JS something to play with, but it breaks Rails assets that use ERB.  For instance, one might have a file like `sprites.css.erb`, which is a CSS file that relies on Rails helpers.

If any files like this exist in the directory specified by `source` in the yaml config, Hologram will either generate a `sprites.css` file in `destination` directory, or crash if the file needs any Rails helpers.

Perhaps Hologram's `DocBuilder` could only call `write_erb` if the file looks like it's either a straight ERB file, ie: `readme.erb` or an html erb file like `readme.html.erb`, and just document the file otherwise.

**Comment by jdcantrell** [comment]
Went with:

```
ignore_paths:
  - "*.erb"
  - my_file.scss
```

**Comment by jdcantrell** [comment]
Went with:

```
ignore_paths:
  - "*.erb"
  - my_file.scss
```

**Comment by jdcantrell** [comment]
Went with:

```
ignore_paths:
  - "*.erb"
  - my_file.scss
```

**Comment by adamsanderson** [comment]
Hey, thanks for taking care of this.

**Comment by jdcantrell** [comment]
NP! Sorry for the triple comment, not sure what I was doing when that happened.

**Comment by wwcline** [comment]
Adding the `ignore_paths` option in #213 solves the problem where you don't want Hologram to treat every ERb as if it were a style guide page, but it also seems to prevent Hologram from processing documentation blocks inside ERb files.

> For instance, one might have a file like sprites.css.erb, which is a CSS file that relies on Rails helpers.

In my case, I have  `.css.erb` files that contain documentation blocks. Hologram is processing the ERb and putting files like `sprites.css` in my output directory. I can stop that behavior by setting `ignore_paths` but in neither case will `sprites.css.erb`’s documentation blocks appear anywhere in the output pages.

**Comment by wwcline** [comment]
The problematic code seems to be this:

https://github.com/trulia/hologram/blob/master/lib/hologram/doc_parser.rb#L89

Am I correct in understanding that `.erb` files will *never* be scanned for documentation blocks, as Hologram works currently?
