### ISSUE TITLE
Dependencies does not get copied on Windows machine

### ISSUE THREAD

**Issue by rmatsumoto** [trulia/hologram#148]
Hi, this is my very first bug report, so please go easy on me if I missed any details :)

On my Windows 7 Parallel machine I've got following environment

```
- ruby 2.0.0p481 (2014-05-08) [i386-mingw32]
- hologram (1.2.0)
```

Also with actual machine with following environment with exactly same folder structure

```
- ruby 1.9.3
- hologram (1.2.0)
```

With following folder structure

```
Base--
     |-css
     |-scss
     |-js
     |-images
```

and following config.yml file:

```
source: 
    - ./scss
    - ./js
destination: ./docs
documentation_assets: ./doc_assets
dependencies:
  - ./css
  - ./images
```

When I run hologram config.yml, i get following warnings:

```
Warning: Could not copy dependency: ./css
Warning: Could not copy dependency: ./images
Build completed. (-:
```

Hologram builds fine with _header and _footer and everything seems to be working except for copying folders declared in dependencies

I copied the entire folder to my Mac with following setup and everything worked fine (including dependencies copying):

```
- ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
- hologram (1.2.0)
```

Not exactly sure what the issue is, maybe something to do with my permission? (I was running command prompt in admin mode) or maybe issue with folder structure?

**Comment by briansmithbeta** [comment]
I am still experiencing this bug with an installation I conducted today. I apologize in advance for my newb comment markdown skills. 

Installation process: 
Prep work:
On my first attempt to run `gem install hologram` I received an error pertaining to "redcarpet" so I followed the instructions in the error and:
1. Went to http://rubyinstaller.org/downloads/
2. Downloaded https://github.com/downloads/oneclick/rubyinstaller/DevKit-tdm-32-4.5.2-20111229-1559-sfx.exe
3. Installed according to instructions on https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

After that prep work, I proceeded with the actual install of what I needed:

1. I ran `gem install redcarpet` with success.
2. I ran `gem install hologram` with success.


Environment: 
OS: Windows 7 Pro 64-bit

    ruby -v
    ruby 1.9.3p55 (2014-11-13) [i386-mingw32]
    
    redcarpet -v
    Redcarpet 3.2.2
    
    hologram -v
    hologram 1.2.0

Could this be an issue with the version of Ruby I am using?

**Comment by jdcantrell** [comment]
Can you try the development version of hologram? It should be fixed there (you can use the specific_install gem to aid this (https://github.com/rdp/specific_install). I'm hoping to relase 1.3 today or tomorrow so optionally you could wait until then.

**Comment by davidgebbett** [comment]
Hi,

I am also seeing this bug, 

Running: 
Windows 10
`ruby 1.9.3p551 (2014-11-13) [i386-mingw32]` (with DevKit)
`Redcarpet 3.3.4`
`hologram 1.4.0`

I have also tried with running Ruby 2.2.4 (x64 & x86 versions).

Any ideas form me try?

Thanks in advance!
