### ISSUE TITLE
Process html_example from a html file

### ISSUE THREAD

**Issue by adiospace** [trulia/hologram#164]
Hi guys,

Is there an easy way to process the html_example from a html file instead of inline comments? 

I'm thinking this will keep things cleaner and with the benefit of html code highlighting.

**Comment by iammikecohen** [comment]
@micahgodbolt can you add a little detail to this? I am trying to share partials between hologram and a static site generator. What template engine did you use with grunt? You are running a task that replaces placeholders in your compiled CSS?

**Comment by micahgodbolt** [comment]
@iammikecohen We started out using Swig. It's a bit crazy, but you can write a CSS file with a swig import statement up in the comment block and after you process the file, you'll have a CSS file with all of the HTML.

**Comment by iammikecohen** [comment]
@micahgodbolt that works great! Thank you. I was struggling to find a way to deliver a static site and a hologram style guide that share HTML partials.
