### ISSUE TITLE
Add optional "copy" button for code examples - or be able to modify the way code examples render

### ISSUE THREAD

**Issue by gpleiss** [trulia/hologram#170]
@montypivotal designed this styleguide for us. We want to have a copy button for our code examples, as seen in the mockup.

![styleguide](https://cloud.githubusercontent.com/assets/824157/4493291/391b7356-4a48-11e4-80e7-c378701d21bd.png)

It looks like adding a copy button is pretty simple with [ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard). However, we need to modify the code example template to get the copy buttons in there.

A few implementation options:

1. On our project, we could extend the `Hologram::MarkdownRenderer` and override the `block_code` method so it creates a copy button. (So no PR)

1. We think that others might like a copy button on their styleguides, so we could make a PR to include a configurable options that adds copy buttons.

1. To make this even more configurable, there could be a option to change the code example template. For example, you could include a `_code_example.html` file to your documentation assets folder that looks something like this:

  ```html
  <div class="codeExample">
    <div class="exampleOutput">
      <%= rendered_example %>
    </div>
    <div class="codeBlock">
      <div class="highlight">
        <pre>
          <%= code_example %>
        </pre>
      </div>
    </div>
    <button class="copy-button" data-clipboard-text="Copy Me!" title="Click to copy me.">
      Copy to Clipboard
    </button>
  </div>
  ```

We'd be willing to submit a PR for any of these options :) What do you think is best?

@gpleiss, @bebepeng, @drpep, @stubbornella

**Comment by jdcantrell** [comment]
Seems like this is fixed (-:

**Comment by menno79** [comment]
How do I implement ZeroClipboard? I'm having trouble passing a unique identifier for the id-attribute to use as a 'data-clipboard-target'. Any help would be much appreciated.
