### ISSUE TITLE
index.md: a documentation error or a bug?

### ISSUE THREAD

**Issue by epicyclist** [trulia/hologram#173]
The documentation for `index` in the config states:

> Mark which category should be the index page
> Alternatively, you may have an index.md in the documentation assets
> folder instead of specifying this config.

However, this only works when index.md is within the `source` path. I also noticed that the [hologram-example](https://github.com/trulia/hologram-example) project is doing this: index.md is under components (`source`), not templates (`documentation_assets`).

I think the way it's documented now should be the correct behavior: I prefer having the index with the documentation assets.

Thoughts?

**Comment by redoPop** [comment]
Looks like this was fixed by #202.

**Comment by epicyclist** [comment]
This was not fixed by #202: only documented.

**Comment by sethwhitaker** [comment]
I concur, It would be nice to be able to put the `index.md` in the `documentation_assets` folder instead of the sass source folder.

**Comment by chansecampbell** [comment]
Just giving this a little bump as I've just had the same issue with the `index.md` having to be placed within the src assets folder.
