### ISSUE TITLE
Index page title incorrect

### ISSUE THREAD

**Issue by charliecm** [trulia/hologram#190]
When I set `index: base` in the config file, the generated `index.html` has an title of a different section in the doc instead. It seems to default to the last category parsed even though it should set the `title` variable to the category assigned to `index`.

**Comment by fatastronauts** [comment]
I am seeing this as well. The last item in the navigation is also set to active. The navigation issue might be theme related though, I am using the Cortana theme.

**Comment by saviomuc** [comment]
confirming this issue.
