### ISSUE TITLE
References to components output as literal text

### ISSUE THREAD

**Issue by mattgarrish** [trulia/hologram#191]
I've tried using this syntax from the manual for linking: [link description][component_name]

But the brackets and text get output as literal text instead of a link. I've checked that the component name matches. The only way I can get the links to output is to reference the category file as a standard link: [link description](category.html#component_name). Even local references don't work.

Something I'm missing?

Using hologram 1.2.0 with ruby 1.9.3p545 on win7.

**Comment by nilshendriks** [comment]
Same here.

**Comment by gpleiss** [comment]
This feature has been added since the last release of Hologram. If you use the latest development version it should work.

**Comment by mattgarrish** [comment]
Ah, thanks, that was my problem!

New problem, though: the generated xrefs are all absolute, so the output linking is only usable from a web/drive root. Any way the preceding slashes can be removed?

**Comment by gpleiss** [comment]
At the moment, no. My team uses a simple connect server to serve our
styleguide so the preceding slashes work for us.
It sounds like a configurable option - like `hologram_root` or something
like that - would be a good thing for this feature.

Geoffrey Pleiss
(408) 338-8247

**Comment by mattgarrish** [comment]
Agree, fwiw. Even just allowing the option to generate absolute or relative paths would be a big help.

**Comment by gpleiss** [comment]
Actually, now that I think about it, I'm pretty sure relative paths would work when we're using a static server as well. I'm now thinking that there aren't any cases where an absolute path would be necessary over a relative path. I'd be down to just make the links relative paths.
