### ISSUE TITLE
Add support for overriding supported extensions

### ISSUE THREAD

**Issue by fatastronauts** [trulia/hologram#196]
I have really been enjoying Hologram a lot. One minor gripe I am having is with the files that are parsed. I would like to block sub directories or have hologram ignore .scss files. I have a few factory functions that generate classes and their markdown. When Hologram sees the function that generates the markdown it is parsing that function and either throwing an error or adding the function into the style guide which looks broken to users.

Could you add support for removing a supported extension or blocking a subdirectory?

**Comment by jdcantrell** [comment]
We've discussed adding an ignore config option for files and directories that would take care of this. At this time though it's still on the todo list.

**Comment by rearadmiral** [comment]
:+1: to this. We're monkey patching '.rb' into the extensions at the moment.

**Comment by jdcantrell** [comment]
You should be able to do this now:


```
ignore_paths:
  - "ruby_codes/*"
  - my_file.scss
```

**Comment by fatastronauts** [comment]
Thank you @jdcantrell this was very helpful.
