### ISSUE TITLE
Sorting categories

### ISSUE THREAD

**Issue by saviomuc** [trulia/hologram#200]
Hi,

is it possible to sort categories? I didn't find out how the logic for that works.

Cheers

**Comment by jdcantrell** [comment]
I believe they are already sorted alphabetically? For Trulia's styleguide the header has hardcoded links to the category pages and we order those as we wish.

**Comment by creativecoder** [comment]
Actually, categories seem to appear in the order that they get created.

I was able to sort the categories by adding this to my _header.html file for the styleguide, which sorts alphabetically by category name (I don't use ruby regularly, so if there's a better way to sort, please correct me).

```ruby
<% @categories = @categories.sort { |a,b| a[0].downcase <=> b[0].downcase } %>
```

**Comment by jdcantrell** [comment]
This seems like a reasonable way to do it to me.

**Comment by ryanmclaughlin** [comment]
@creativecoder Thanks for that. Any ideas on how to control the ordering? I really don't want by creation date or alphabetical – manual is the way I need!

**Comment by jdcantrell** [comment]
You can create modify the _header.html file (inside hologram's assets folder) and hard code the category links in the desired order. Would this work for what you're wanting to do?

**Comment by ryanmclaughlin** [comment]
@jdcantrell Sure, that works I guess. It'd be nice to have this more dynamic as an option in the config perhaps, or even use the `index:` to be an optional list as well, e.g., `index: intro, elements, components, brand` etc. 

Thanks!

**Comment by mstenquist** [comment]
+1
