### ISSUE TITLE
Arabic Texts are not rendering properly.

### ISSUE THREAD

**Issue by abrahamjagadeesh** [trulia/hologram#207]
![image](https://cloud.githubusercontent.com/assets/6632159/6544958/45f153a6-c582-11e4-8c26-1825966126af.png)

**Comment by jdcantrell** [comment]
Can you provide an example file? I'd like to look in this more closely.

**Comment by abrahamjagadeesh** [comment]
I was adding the charset at top of my .scss file.

@charset "UTF-8";

when I removed the charset, the issue was resolved.

**Comment by jdcantrell** [comment]
Oh thanks for the update!

**Comment by abrahamjagadeesh** [comment]
Thank you for your great work.
