### ISSUE TITLE
Ignore specific file types

### ISSUE THREAD

**Issue by jaylaw81** [trulia/hologram#231]
Is it possible to ignore specific file types? For instance, my project uses compass to output CSS files that contain style documentation, however I want to ignore all .scss files so i can parse JS / JSX files in the same source directory. Otherwise I get errors saying I have duplicate title / category names for an element.

**Comment by iammikecohen** [comment]
You sure can! I asked for this feature a while back for the same reason. In your config.yml use the ignore_paths setting:

ignore_paths:
  - "*.scss"
