### ISSUE TITLE
Possible to access rails helpers in hologram

### ISSUE THREAD

**Issue by misscs** [trulia/hologram#238]
Is it possible to access rails helpers such as `<%= stylesheet_link_tag %>` within the `_header.html` file? When we deploy, our assets get a hash for caching. Hardcoding the path the styles breaks when we move from local to production. 

Thanks in advance

**Comment by edbury** [comment]
I'd also love an answer to this!

**Comment by jdcantrell** [comment]
Right now there is not a way to do this within hologram. There might be a way to do it directly in the erb, but I don't know how you'd do that.
