### ISSUE TITLE
Does not work for Rails 4.0.x projects utilizing the Asset Pipeline

### ISSUE THREAD

**Issue by acconrad** [trulia/hologram#241]
Running the `hologram` command line tool generates from `_header.html` with the following stylesheets:

``` html
<link rel="stylesheet" href="./your_stylesheet_here.css">
```

The problem is that the asset pipeline no longer allows this file structure since assets are timestamped and do not live in that folder in such a static fashion.

**Comment by amiuhle** [comment]
`<link rel="stylesheet" href="/assets/application.css">` works fine.
