### ISSUE TITLE
adding Sass's multi-line comment syntax to docs

### ISSUE THREAD

**Issue by gvinter** [trulia/hologram#84]
I imagine using Hologram in addition to my normal Compass or SassC compiling, not in place of it.

To do this without getting errors, you need to use Sass's multi-line comments "//". but the docs only have single line: "/*".

I'm sure future developers would appreciate that in the docs, it's a bit of a nuance.

**Comment by jamierytlewski** [comment]
I know this issue is closed and I've seen it brought up a couple of times, but what would be nice is to allow single-line comments for those that use linting programs and have setup for single line comments.

**Comment by jdcantrell** [comment]
Hmm, what change are you looking?
