### ISSUE TITLE
Replace Redcarpet markdown processor with kramdown

### ISSUE THREAD

**Issue by mikezx6r** [trulia/hologram#90]
http://kramdown.gettalong.org/index.html

I've been using Middleman for some site generation, and it uses kramdown. Was trying to do some custom handling of image tags, and eventually discovered that kramdown has some very nice extension features that Redcarpet does not. Also, Redcarpet has a few issues that impacted me directly like not recognizing html5 tags yet, and not supporting lists more than 5 levels deep. 

Examples:
putting {.class} or {#id} after some markup will add the id or class. Can also use standard Ruby hash syntax to add additional attributes.

kramdown also supports markdown within html blocks (http://kramdown.gettalong.org/syntax.html#html-blocks)

<div class="property" markdown="1">
Put any markdown *in here* and it will be processed
</div>

Several other nice features in here, and it appears that it's extensible like Redcarpet.

Obviously this would break everyone's custom renderers, so I thought I'd reach out and see if there's any appetite for this. I may do it regardless just as an exercise in Ruby coding for myself, but if the community wants it too then it's more incentive more me.

**Comment by jdcantrell** [comment]
I am closing this issue for now. If someone would like to take it up let's discuss then.
