### ISSUE TITLE
wrap code semantically

### ISSUE THREAD

**Issue by VinSpee** [trulia/hologram#91]
I know this is currently handled by the markdown parser, but the current code examples and samples are technically semantically incorrect. Code examples are outputted in `<pre>` tags. [According to the W3](http://www.w3.org/TR/html5/grouping-content.html#the-pre-element):

> In the following snippet, a sample of computer code is presented.
> 
> ```
> <p>This is the <code>Panel</code> constructor:</p>
> <pre><code>function Panel(element, canClose, closeHandler) {
>  this.element = element;
>  this.canClose = canClose;
>  this.closeHandler = function () { if (closeHandler) closeHandler() };
> }</code></pre>
> ```

This would not only improve semantics, but allow out-of-the-box compatibility with syntax tools like [Prism.js](http://prismjs.com/)

**Comment by dontwork** [comment]
Is it possible to get these code tags within the pre tags?

It seems weird trying to write a semantically correct document with a well documented style guide and the styleguide gem itself doesn't adhere to the styles in my stylesheet!
